### ISSUE TITLE
hplip not built with scanner support

### ISSUE THREAD

**Issue by drahnr** [CZ-NIC/turris-os-packages#28]
https://forum.turris.cz/t/hplip-not-built-with-scanner-support/3968

**Comment by drahnr** [comment]
where am I supposed to file tickets?

**Comment by ja-pa** [comment]
You can create issue here or in our gitlab https://gitlab.labs.nic.cz/turris/turris-os-packages/issues . 
Anyway copy of your issue is already there (see https://gitlab.labs.nic.cz/turris/turris-os-packages/issues/65 )

Back to hplip
hplip with scanner support is failing during build, so that was reason why it's disabled. I will try to fix it to 3.9.

**Comment by drahnr** [comment]
I was just to say I already posted it there. Tbh it is not very clear where to post issues/feaure requests.

Thanks!

**Comment by ja-pa** [comment]
Duplicate of  https://gitlab.labs.nic.cz/turris/openwrt/issues/58

**Comment by drahnr** [comment]
The link gives a 502 ..

**Comment by ja-pa** [comment]
That should be just temporary gitlab error... If it's still unavailable please let me know and I'll reopen this issue.
